spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        create_empty_composites:
          enabled: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 60000
            readTimeout: 300000

auth:
  google:
    base-url: ${GOOGLE_BASE_URL}
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

jwt:
  refresh-expiration-time: 1296000000 # 15일
  access-expiration-time: 3600000 # 1시간
  prefix: Bearer
  secret-key: ${JWT_SECRET}

